version: "3.9"
networks:
  backend:
  public:
services:
#  app:
#    build: ./client
#    networks:
#      - public
#    depends_on:
#      frontend:
#        condition: service_healthy
  frontend:
    build: ./server
    networks:
      - backend
      - public
    volumes:
      - logs:/var/mylog
      - ./server:/app
    ports:
      - "8000:8000"
    depends_on:
      graphite:
        condition: service_healthy
  loki:
    image: grafana/loki:2.4.0
    volumes:
      - loki-data:/loki
      - ./config/loki:/etc/loki:ro
    ports:
      - "3100:3100"
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - backend
#  promtail:
#    image: grafana/promtail:2.4.0
#    volumes:
#      - logs:/var/mylog:ro
#      - ./config/promtail:/etc/promtail:ro
#    restart: unless-stopped
#    command: -config.file=/etc/promtail/promtail-config.yml
#    networks:
#      - backend
  fluentbit:
    image: fluent/fluent-bit
    volumes:
      - logs:/var/mylog:ro
      - ./config/fluentbit:/etc/fluentbit:ro
    restart: unless-stopped
    command: -c /etc/fluentbit/pipeline.conf -R /etc/fluentbit/parsers.conf
    networks:
      - backend
  grafana:
    image: grafana/grafana:latest
    user: "1000"
    volumes:
      - grafana-lib:/var/lib/grafana
      - grafana-log:/var/log/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - backend
  graphite:
    image: prom/graphite-exporter
    restart: unless-stopped
    networks:
      - backend
    ports:
      - "9108:9108"
      - "9109:9109"
    healthcheck:
      test: netstat -tlnu | grep ":9109"
      interval: 15s
      timeout: 3s
      retries: 1
  prometheus:
    image: prom/prometheus
    volumes:
      - prometheus-data:/prometheus
      - ./config/prometheus:/etc/prometheus
    restart: unless-stopped
    networks:
      - backend
    ports:
      - "9090:9090"

volumes:
  logs:
  grafana-lib:
  grafana-log:
  prometheus-data:
  loki-data:

